# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.cache/wt [current_project]
set_property parent.project_path C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/shifter.v
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/lzdetector.v
}
read_verilog -library xil_defaultlib {
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/twobitlzd.v
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/logp.v
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/taus.v
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/sqrtp.v
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/cosp.v
  C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/sources_1/new/AWGN_FINAL.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/logp/new/logp_ooc.xdc
set_property used_in_implementation false [get_files C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/logp/new/logp_ooc.xdc]

read_xdc C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Compy/Desktop/TexasLDPC/AWGN/AWGN.srcs/constrs_1/new/constraints.xdc]


synth_design -top AWGN_FINAL -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef AWGN_FINAL.dcp

catch { report_utilization -file AWGN_FINAL_utilization_synth.rpt -pb AWGN_FINAL_utilization_synth.pb }
